sudo: false
language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
  
script: "./travis.sh"
cache:
  directories:
    - .cache
before_script:
 - chmod +x travis.sh

env:
  - PHPSTORM_ENV=8
  - PHPSTORM_ENV=9
  - PHPSTORM_ENV=10
  - PHPSTORM_ENV=10eap
  
matrix:
  allow_failures:
    - env: PHPSTORM_ENV=10
    - env: PHPSTORM_ENV=10eap